-- Clean Mowazana source of truth. Apply with `supabase db push` before deploying.
create extension if not exists pgcrypto;
create type public.muwazana_role as enum ('member','manager');
create type public.transaction_type as enum ('expense','payment','loan_payment','reward','penalty');
create type public.transaction_status as enum ('pending','on_hold','approved','rejected');
create type public.loan_status as enum ('draft','active','suspended','completed','cancelled');
create type public.installment_status as enum ('upcoming','due','overdue','partial','paid','carried_forward','cancelled');
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, email text unique not null, name text not null, color text not null default '#4f8f78', role public.muwazana_role not null default 'member', active boolean not null default true, created_at timestamptz not null default now());
create table public.loans (id uuid primary key default gen_random_uuid(), member_id uuid not null references public.profiles(id), title text not null, principal_amount numeric(14,2) not null check(principal_amount>0), interest_rate numeric(8,2) not null default 0, interest_amount numeric(14,2) not null, total_amount numeric(14,2) not null, remaining_amount numeric(14,2) not null, installment_count integer not null check(installment_count>0), installment_amount numeric(14,2) not null, start_date date not null, status public.loan_status not null default 'draft', notes text not null default '', created_by uuid not null references public.profiles(id), created_at timestamptz not null default now());
create table public.installments (id uuid primary key default gen_random_uuid(), loan_id uuid not null references public.loans(id) on delete cascade, member_id uuid not null references public.profiles(id), title text not null, installment_number integer not null, installment_count integer not null, base_amount numeric(14,2) not null, carry_in_amount numeric(14,2) not null default 0, amount numeric(14,2) not null, paid_amount numeric(14,2) not null default 0, remaining_amount numeric(14,2) not null, due_date date not null, status public.installment_status not null default 'upcoming', unique(loan_id, installment_number));
create table public.transactions (id uuid primary key default gen_random_uuid(), member_id uuid not null references public.profiles(id), type public.transaction_type not null, title text not null, amount numeric(14,2) not null check(amount>0), occurred_at timestamptz not null default now(), status public.transaction_status not null default 'pending', note text not null default '', manager_note text, loan_id uuid references public.loans(id), installment_id uuid references public.installments(id), evidence_path text, created_by uuid references public.profiles(id), approved_by uuid references public.profiles(id), approved_at timestamptz, created_at timestamptz not null default now(), check ((type='loan_payment') = (installment_id is not null)));
create table public.penalty_objections (id uuid primary key default gen_random_uuid(), transaction_id uuid unique not null references public.transactions(id) on delete cascade, member_id uuid not null references public.profiles(id), text text not null check(char_length(text) between 2 and 1000), status text not null default 'pending' check(status in ('pending','accepted','rejected')), deadline_at timestamptz not null, decision_note text, decided_by uuid references public.profiles(id), decided_at timestamptz, created_at timestamptz not null default now());
create table public.notifications (id uuid primary key default gen_random_uuid(), recipient_id uuid not null references public.profiles(id), audience text not null default 'member' check(audience in ('member','manager')), event text not null, title text not null, body text not null, entity_type text, entity_id uuid, payload jsonb not null default '{}', read_at timestamptz, created_at timestamptz not null default now());
create table public.audit_log (id uuid primary key default gen_random_uuid(), actor_id uuid references public.profiles(id), action text not null, entity_type text not null, entity_id uuid not null, before_values jsonb, after_values jsonb, note text, created_at timestamptz not null default now());
create table public.idempotency_keys (request_key text primary key, member_id uuid not null references public.profiles(id), entity_id uuid not null references public.transactions(id), created_at timestamptz not null default now());
create table public.outbox_events (id uuid primary key default gen_random_uuid(), event_key text unique not null, payload jsonb not null, attempts integer not null default 0, next_attempt_at timestamptz not null default now(), sent_at timestamptz, last_error text, created_at timestamptz not null default now());
alter table public.profiles enable row level security; alter table public.transactions enable row level security; alter table public.loans enable row level security; alter table public.installments enable row level security; alter table public.notifications enable row level security; alter table public.penalty_objections enable row level security;
create function public.is_manager() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from profiles where id=auth.uid() and active and role='manager') $$;
create policy "own profile" on public.profiles for select using(id=auth.uid() or public.is_manager());
create policy "own transactions" on public.transactions for select using(member_id=auth.uid() or public.is_manager());
create policy "own loans" on public.loans for select using(member_id=auth.uid() or public.is_manager());
create policy "own installments" on public.installments for select using(member_id=auth.uid() or public.is_manager());
create policy "own notifications" on public.notifications for select using(recipient_id=auth.uid());
create policy "own objections" on public.penalty_objections for select using(member_id=auth.uid() or public.is_manager());
insert into storage.buckets(id,name,public) values('evidence','evidence',false) on conflict do nothing;
create policy "private evidence" on storage.objects for select using(bucket_id='evidence' and (owner=auth.uid() or public.is_manager()));

create function public.create_transaction(p_member_id uuid,p_type public.transaction_type,p_title text,p_amount numeric,p_occurred_at timestamptz,p_note text,p_installment_id uuid,p_request_key text,p_status public.transaction_status default 'pending') returns public.transactions language plpgsql security definer set search_path=public as $$
declare result public.transactions; target public.installments;
begin
 if not public.is_manager() and p_member_id<>auth.uid() then raise exception 'forbidden'; end if;
 select * into result from transactions where id=(select entity_id from idempotency_keys where request_key=p_request_key); if found then return result; end if;
 if p_type='loan_payment' then select * into target from installments where id=p_installment_id and member_id=p_member_id for update; if not found or target.remaining_amount<p_amount then raise exception 'invalid installment'; end if; end if;
 insert into transactions(member_id,type,title,amount,occurred_at,note,installment_id,loan_id,status,created_by,approved_by,approved_at) values(p_member_id,p_type,p_title,p_amount,p_occurred_at,p_note,p_installment_id,target.loan_id,p_status,auth.uid(),case when p_status='approved' then auth.uid() end,case when p_status='approved' then now() end) returning * into result;
 insert into idempotency_keys values(p_request_key,p_member_id,result.id); insert into outbox_events(event_key,payload) values(result.id::text,jsonb_build_object('transactionId',result.id,'type',result.type,'memberId',result.member_id)) on conflict do nothing; return result;
end $$;
create function public.transition_transaction(p_id uuid,p_actor_id uuid,p_action text,p_note text) returns public.transactions language plpgsql security definer set search_path=public as $$ declare result public.transactions; begin if not public.is_manager() then raise exception 'forbidden'; end if; select * into result from transactions where id=p_id for update; if not found or result.status not in ('pending','on_hold') then raise exception 'invalid transition'; end if; update transactions set status=case p_action when 'approve' then 'approved' when 'hold' then 'on_hold' when 'reject' then 'rejected' else result.status end,manager_note=p_note,approved_by=case when p_action='approve' then p_actor_id end,approved_at=case when p_action='approve' then now() end where id=p_id returning * into result; if p_action='approve' and result.type='loan_payment' then update installments set paid_amount=paid_amount+result.amount,remaining_amount=remaining_amount-result.amount,status=case when remaining_amount-result.amount=0 then 'paid' else 'partial' end where id=result.installment_id; update loans set remaining_amount=remaining_amount-result.amount where id=result.loan_id; end if; insert into audit_log(actor_id,action,entity_type,entity_id,note) values(p_actor_id,p_action,'transaction',p_id,p_note); return result; end $$;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,email,name) values(new.id,lower(new.email),coalesce(new.raw_user_meta_data->>'name',split_part(new.email,'@',1))) on conflict(id) do update set email=excluded.email; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
